# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
pet1=Pet.create(name:'SnowFlake',age:1,breed:'American Eskimo',location:'Brooklyn',photo:'https://i.etsystatic.com/6017700/r/il/cc00bc/1440852274/il_794xN.1440852274_zwy2.jpg',description:'Neither shy nor aggressive, Eskies are always alert and friendly, though a bit conservative when making new friends.')
pet2=Pet.create(name:'Piper',age:1,breed:'Australian Cattle',location:'Brooklyn',photo:'https://i.pinimg.com/736x/3d/60/e9/3d60e948872b0cf4a3df756278750c61--blue-heelers-australian-cattle-dog.jpg',description:'They hava a natural affinity for obedience and enjoys playtime')
pet3=Pet.create(name:'Brownie',age:3,breed:'Beagle',location:'Queens',photo:'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/13000937/Beagle-On-White-07.jpg',description:'Not only is the Beagle an excellent hunting dog and loyal companion, it is also happy-go-lucky, funny, and—thanks to its pleading expression—cute.')
pet4=Pet.create(name:'Spirit',age:3,breed:'Cardigan Welsh Corgi',location:'Queens',photo:'https://www.dogbreedslist.info/uploads/allimg/dog-pictures/Cardigan-Welsh-Corgi-1.jpg',description:'Cardis are trainable, faithful, and vigilant guardians with a “big dog” bark.')
pet5=Pet.create(name:'Silky',age:2,breed:'Afghan Hound',location:'New York',photo:'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/14145006/Afghan-Hound.86820153.jpg',description:'Afghans are independent, dignified, and aloof in general, but they are affectionate and extremely loyal to humans they have bonded with.')
pet6=Pet.create(name:'WilmsFord',age:2,breed:'Cesky Terrier',location:'New York',photo:'https://vetstreet.brightspotcdn.com/dims4/default/e6a995a/2147483647/thumbnail/645x380/quality/90/?url=https%3A%2F%2Fvetstreet-brightspot.s3.amazonaws.com%2F04%2Fd6%2F5bd898f44eb08d58ecf40becffbd%2Fcesky-terrier-1.jpg',description:'The Cesky Terrier, national dog of the Czech Republic, is a clever and adventurous playmate for kids and an eager walking buddy for the folks. ')
pet7=Pet.create(name:'JigglyPuff',age:1,breed:'Coton de Tulear',location:'Long Island',photo:'https://images1.americanlisted.com/nlarge/coton-de-tulear-puppy-for-sale-adoption-rescue-americanlisted_114662633.jpg',description:'The Coton de Tulear, “Royal Dog of Madagascar,” is a bright, happy-go-lucky companion dog whose favorite activities include clowning, cavorting, and following their special human around the house.')
pet8=Pet.create(name:'Draco',age:1,breed:'Norrbottenspets',location:'Long Island',photo:'https://www.dogbreedslist.info/uploads/allimg/dog-pictures/Norrbottenspets-2.jpg',description:'They are a small-sized hunting dog of Spitz-type, which was thought to be extinct but survived as a farm and hunting dog in the Northern parts of Sweden and Finland.')
pet9=Pet.create(name:'Pixxie',age:2,breed:'Lhasa Apso',location:'Bronx',photo:'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/09130555/Lhasa-Apso.jpg',description:'Smart,confident, and complex, Lhasas are family comedians but regally aloof with strangers.')
pet10=Pet.create(name:'Chanel',age:3,breed:'StabyHoun',location:'Bronx',photo:'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/26173552/Stabyhoun.30135865.jpg',description:'Although occasionally somewhat willful by nature, Stabyhouns are obedient, gentle, and patient dogs, who are deeply fond of their family, wanting to please their owners.')

owner1=Owner.create(name:'Mary',age:36,email:'Mary&ThePussyCats@fakemail.com',phone_number:'212-336-0087',location:'New York',photo:'https://d2ck0sxsjau14o.cloudfront.net/wp-content/uploads/2018/10/young-attractive-woman.jpg',description:' Mom of 3 with the love and Home for a lil puppy. I have have dogs in the past and is currently Searching for my fury baby!')
owner2=Owner.create(name:'Steph',age:28,email:'StephCurryWitThePot@fakemail.com',phone_number:'178-002-3367',location:'New York',photo:'https://cdn.pixabay.com/photo/2017/08/07/00/33/people-2597995_960_720.jpg',description:'Looking for a show stopper, Full with spunk and is easy to train. Currently have 2 small dogs in need of a bestie.')
owner3=Owner.create(name:'Mark & Beth',age:42,email:'DogLovers200@fakemail.com',phone_number:'876-209-9981',location:'Brooklyn',photo:'https://cdn1-www.dogtime.com/assets/uploads/2018/01/dog-lover-dating-tips-9.jpg',description:'We are a Fun lovingg couple with no children looking to fill a missing piece in our puzzle. Low mantainence Preferred!, Hypoallergenic a must!')
owner4=Owner.create(name:'Kevin',age:37,email:'KevMaster212@fakemail.com',phone_number:'718-900-3000',location:'Brooklyn',photo:'https://files.insidify.com/uploads/discovery/happy-black-man.png',description:'Single Dad with 7 year old son, Looking for the best kitty for him to bond with!')
owner5=Owner.create(name:'Charles',age:41,email:'KittyMan44@fakemail.com',phone_number:'917-213-0213',location:'Queens',photo:'https://i.dailymail.co.uk/i/pix/2014/04/16/article-2606478-1D26D5FA00000578-317_634x424.jpg',description:'Cat lover at heart, If It was up to me Id have a santuary full of them!... Looking to add another furry feline to mix.')
owner6=Owner.create(name:'Suzanne',age:45,email:'vetLA@fakemail.com',phone_number:'770-876-2346',location:'Queens',photo:'https://blogdottwomenandatruckdotcom.files.wordpress.com/2015/07/dr.jpg',description:'My profession surrounds me around animals every day, Now looking for my own to love and shelter.')
owner7=Owner.create(name:'Iyanna',age:45,email:'teacherByday@fakemail.com',phone_number:'425-228-2876',location:'Long Island',photo:'https://www.sheknows.com/wp-content/uploads/2018/08/woman-and-dog-2_nf6gmq.jpeg',description:'Teacher by day and lonely at night. Would love to have a furry friend waiting at home for me!')
owner8=Owner.create(name:'Ethel',age:55,email:'granniesWithFannies@fakemail.com',phone_number:'347-445-0098',location:'Long Island',photo:'',description:'Widowed and in need of some company. After my husband passed I havent had to care for anyone. I miss being depended upon...Looking for my new best friend.')
owner9=Owner.create(name:'Sadia',age:19,email:'freshmanOfASU@fakemail.com',phone_number:'646-872-1123',location:'Bronx',photo:'https://collegelifemadeeasy.com/wp-content/uploads/2017/11/r.jpg',description:'Just graduated High school and off to college in a few weeks, Currently looking for my new dorm pet to take along the ride.')
owner10=Owner.create(name:'Sole',age:28,email:'soul2soul@fakemail.com',phone_number:'646-887-9987',location:'Bronx',photo:'https://www.stylevore.com/wp-content/uploads/2018/09/39401512_2063246623708010_8403980869068390400_n-700x875.jpg',description:'Ive dealt with depression for years in college, I was told that I was Crazy and lots of people never understood me. So I want to start building a bond with a furry buddy to help boost my confidence to speak to others.')


owner1.pets.push(pet1, pet2)
owner2.pets.push(pet3, pet4)
owner3.pets.push(pet5)
owner4.pets.push(pet6, pet7,pet8)
owner5.pets.push(pet10)
